
The following have been reloaded with a version change:
  1) python/.3.11.4 => python/3.11.4

INFO:root:Loading data...
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_type', 'gene_name', 'level', 'mgi_id', 'havana_gene', 'transcript_id', 'transcript_type', 'transcript_name', 'transcript_support_level', 'tag', 'havana_transcript', 'exon_number', 'exon_id', 'protein_id', 'ccdsid', 'ont']
INFO:root:Extracted GTF attributes: ['transcript_id', 'gene_id', 'gene_name']
INFO:root:Mapping ORFs to gencode...
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
WARNING:root:no coding start found
INFO:root:Calling ORFs...
Empty DataFrame
Columns: [ID, pb_acc, misc, orf, orf_start]
Index: []
  seqname  ...                     gene_name
0    chr1  ...                         10453
1    chr1  ...                         10453
2    chr1  ...  ENSMUSG00000033845.14_Mrpl15
3    chr1  ...  ENSMUSG00000033845.14_Mrpl15
4    chr1  ...  ENSMUSG00000033845.14_Mrpl15

[5 rows x 11 columns]
['gene' 'transcript' 'exon' 'CDS' 'start_codon' 'stop_codon' 'UTR'
 'Selenocysteine']
Traceback (most recent call last):
  File "00_scripts/05_mando_orf_calling.py", line 300, in <module>
    main()
  File "00_scripts/05_mando_orf_calling.py", line 279, in main
    orfs = orf_calling_multiprocessing(all_orfs, pool, 1, results.num_cores)
  File "00_scripts/05_mando_orf_calling.py", line 240, in orf_calling_multiprocessing
    called_orf = pd.concat(called_orf_list)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 295, in concat
    sort=sort,
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
INFO:root:Loading data...
Traceback (most recent call last):
  File "00_scripts/05_orf_calling.py", line 307, in <module>
    main()
  File "00_scripts/05_orf_calling.py", line 267, in main
    orf_coord = read_orf(results.orf_coord)
  File "00_scripts/05_orf_calling.py", line 188, in read_orf
    orf[['pb_acc', 'misc', 'orf']] = orf['ID'].str.split('_', expand=True)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3160, in __setitem__
    self._setitem_array(key, value)
  File "/opt/conda/envs/lrpg/lib/python3.7/site-packages/pandas/core/frame.py", line 3186, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
